services:
  app:
    build: .
    stdin_open: true 
    tty: true
    container_name: capital_game_app
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=player
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=capital_play

  db:
    image: mysql:8.0
    container_name: capital_game_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "player", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: capital_play
      MYSQL_USER: player
      MYSQL_PASSWORD: secret
    
    stdin_open: true 
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: